"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z3qkfc9zn+&ejjw5gpl1&axc)tbwk2jbk__mzlx(24@pr-$tn+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DJANGO_TELEGRAMBOT = {
    'MODE': 'WEBHOOK',  # Режим работы - вебхук
    'WEBHOOK_SITE': 'https://mywebsite.com',  # Ссылка на ваш веб-сайт
    'WEBHOOK_PREFIX': '/prefix',  # Префикс для вебхука (необязательно)
    'BOTS': [
        {
            'TOKEN': '123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11',  # Токен вашего бота

            # Другие возможные настройки:
            # 'ALLOWED_UPDATES': ['message', 'edited_channel_post', 'callback_query'],  # Разрешенные типы обновлений
            # 'TIMEOUT': 10,  # Таймаут ожидания ответа от сервера
            # 'WEBHOOK_MAX_CONNECTIONS': 40,  # Максимальное количество одновременных соединений с вебхуком
            # 'POLL_INTERVAL': 0.0,  # Интервал опроса сервера Telegram (если используется режим POLLING)
            # 'POLL_CLEAN': False,  # Очищать ли ожидающие обновления на сервере Telegram перед началом опроса
            # 'POLL_BOOTSTRAP_RETRIES': 0,  # Количество попыток повторного подключения при запуске бота
            # 'POLL_READ_LATENCY': 2,  # Время ожидания ответа от сервера Telegram
        },
        # Другие боты здесь с тем же форматом
    ],
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainshop',
    'django_telegrambot',

]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1200
SESSION_SAVE_EVERY_REQUEST = True

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'
ASGI_APPLICATION = "myshop.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Переменная для определения, следует ли запускать ботов
RUN_BOTS = True  # Или False, в зависимости от ваших потребностей

TOKEN_ADMIN = '6969425776:AAEXBAbffPUuJF_I3ekKzh0-z0y_Lk1JwAE'

TOKEN_BOT_CLIENT = '7020363948:AAF7oznvRaebiBkGI9Se7tF622_gKt7dbqI'

PROXY = 'http://103.106.219.87:8085'
