# Generated by Django 5.0.1 on 2024-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$I6KJQs0pfNcQFmMQFbkeeI$eBiwMzEmIlyl3/NDY3+kfWhv4b9/IFqZ2AAesZ5htm4=', max_length=128, verbose_name='password'),
        ),
    ]
