# Generated by Django 5.0.1 on 2024-05-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0007_alter_order_status_orders_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$NEryEc2AsDxVvXpJkiQgVI$pzxObaFbv8uFeQP5Hga5+a1I2YIPpbndc6b9vLj/q/k=', max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('completed_orders', models.IntegerField(default=0)),
                ('information', models.TextField(blank=True, null=True)),
                ('active_orders', models.ManyToManyField(blank=True, related_name='active_executors', to='mainshop.order')),
            ],
        ),
    ]
